version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PORT: "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
    networks:
      - web  

  redis:
    image: redis:latest

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
  
    ports:
      - "8000:8000"
    networks:
      - web
    volumes:
      - /app/  
    depends_on:
      - db
      - redis

networks:
  web: 

volumes:
  postgres_data:
  app:
