version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"  
    
    networks:
      - main  
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  
  
    
  redis:
    image: redis:latest

  web:
    build: .
    command: python manage.py runserver 8000
  
    ports:
      - "8000:8000"
    
    networks:
      - main
    volumes:
      - /app/  
    depends_on:
      - db
      - redis


volumes:
  postgres:
  app:
networks:
  main: